# Week 1 Lesson 1 Python Review

Short review of core concepts in Python exemplified by objects in the Numpy library.

- Recall basic vocabulary
- Practice markdown syntax

## Libraries and packages

**Library:** collection of code that we can use to perform a specific task in our programs. It can be one or multiple files.

**NumPy:**

- Core library for numerical computing
- Many libraries use NumPy arrays as building blocks
- Computations on NumPy objects are optimized for speed an memory usage

Let's import NumPy with its **standard abbreviation** `np`:

In [1]:
import numpy as np

## Variables

**Variable:** a name we assign to a particular object in python

Example:

In [3]:
# Assign a small array to a variable a
a = np.array([[1, 1, 2], [3, 5, 8]])

To view a variables value from jupyer nb:

In [4]:
# Run cell with variable name to show value
a

array([[1, 1, 2],
       [3, 5, 8]])

In [5]:
# Use `print` function to print value
print(a)

[[1 1 2]
 [3 5 8]]
